[2023-09-23T02:06:01.137+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: resume_generation_dag.generate_resume manual__2023-09-23T02:05:57.066379+00:00 [queued]>
[2023-09-23T02:06:01.143+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: resume_generation_dag.generate_resume manual__2023-09-23T02:05:57.066379+00:00 [queued]>
[2023-09-23T02:06:01.144+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-09-23T02:06:01.152+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): generate_resume> on 2023-09-23 02:05:57.066379+00:00
[2023-09-23T02:06:01.156+0000] {standard_task_runner.py:57} INFO - Started process 346 to run task
[2023-09-23T02:06:01.158+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'resume_generation_dag', 'generate_resume', 'manual__2023-09-23T02:05:57.066379+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/resume_generation.py', '--cfg-path', '/tmp/tmp9iq801fx']
[2023-09-23T02:06:01.161+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask generate_resume
[2023-09-23T02:06:01.172+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:188 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-09-23T02:06:01.198+0000] {task_command.py:410} INFO - Running <TaskInstance: resume_generation_dag.generate_resume manual__2023-09-23T02:05:57.066379+00:00 [running]> on host f5f1420c2161
[2023-09-23T02:06:01.252+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='resume_generation_dag' AIRFLOW_CTX_TASK_ID='generate_resume' AIRFLOW_CTX_EXECUTION_DATE='2023-09-23T02:05:57.066379+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-23T02:05:57.066379+00:00'
[2023-09-23T02:06:27.960+0000] {logging_mixin.py:149} INFO - FULL_PATH
[2023-09-23T02:06:27.964+0000] {logging_mixin.py:149} INFO - /opt/***/dags/resumes/Resume_Software Engineer, Android | Ingenieur.e logiciel - Android_Meta.txt
[2023-09-23T02:06:44.831+0000] {logging_mixin.py:149} INFO - FULL_PATH
[2023-09-23T02:06:44.838+0000] {logging_mixin.py:149} INFO - /opt/***/dags/resumes/Resume_Software Engineer II - Machine Learning_Staples.txt
[2023-09-23T02:07:06.683+0000] {logging_mixin.py:149} INFO - FULL_PATH
[2023-09-23T02:07:06.690+0000] {logging_mixin.py:149} INFO - /opt/***/dags/resumes/Resume_Data Analyst/ Process Data Engineer/ Datawarehouse Analyst_Shorewise Consulting.txt
[2023-09-23T02:07:06.702+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/resume_generation.py", line 94, in generate_resume
    resume_gen(v['job_title'],",".join(v["skills"]),v['employer_name'],v['job_apply_link'])
  File "/opt/airflow/dags/resume_generation.py", line 55, in resume_gen
    with open(full_path, 'w') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/resumes/Resume_Data Analyst/ Process Data Engineer/ Datawarehouse Analyst_Shorewise Consulting.txt'
[2023-09-23T02:07:06.732+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=resume_generation_dag, task_id=generate_resume, execution_date=20230923T020557, start_date=20230923T020601, end_date=20230923T020706
[2023-09-23T02:07:06.745+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task generate_resume ([Errno 2] No such file or directory: '/opt/airflow/dags/resumes/Resume_Data Analyst/ Process Data Engineer/ Datawarehouse Analyst_Shorewise Consulting.txt'; 346)
[2023-09-23T02:07:06.782+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-09-23T02:07:06.792+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
