[2023-09-23T02:23:17.413+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: job_extraction_with_task_flow.get_jobs_from_api manual__2023-09-23T02:23:14.194773+00:00 [queued]>
[2023-09-23T02:23:17.419+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: job_extraction_with_task_flow.get_jobs_from_api manual__2023-09-23T02:23:14.194773+00:00 [queued]>
[2023-09-23T02:23:17.420+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-09-23T02:23:17.427+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): get_jobs_from_api> on 2023-09-23 02:23:14.194773+00:00
[2023-09-23T02:23:17.432+0000] {standard_task_runner.py:57} INFO - Started process 270 to run task
[2023-09-23T02:23:17.435+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'job_extraction_with_task_flow', 'get_jobs_from_api', 'manual__2023-09-23T02:23:14.194773+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmptki02wic']
[2023-09-23T02:23:17.437+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask get_jobs_from_api
[2023-09-23T02:23:17.448+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:188 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-09-23T02:23:17.476+0000] {task_command.py:410} INFO - Running <TaskInstance: job_extraction_with_task_flow.get_jobs_from_api manual__2023-09-23T02:23:14.194773+00:00 [running]> on host 51d1724a3329
[2023-09-23T02:23:17.533+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='job_extraction_with_task_flow' AIRFLOW_CTX_TASK_ID='get_jobs_from_api' AIRFLOW_CTX_EXECUTION_DATE='2023-09-23T02:23:14.194773+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-23T02:23:14.194773+00:00'
[2023-09-23T02:23:34.371+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL.py", line 85, in get_jobs_from_api
    nlst+=get_api_data(v)
  File "/opt/airflow/dags/ETL.py", line 48, in get_api_data
    jobs= jsearch.fetch_job_description(job_title + "in Canada")
  File "/opt/airflow/dags/jobportal.py", line 34, in fetch_job_description
    return self.filter_dic(res_dic)
  File "/opt/airflow/dags/jobportal.py", line 21, in filter_dic
    lst=[{key: v[key] for key in keys_list if key in v} for v in res_dic["data"] ]
KeyError: 'data'
[2023-09-23T02:23:40.956+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=job_extraction_with_task_flow, task_id=get_jobs_from_api, execution_date=20230923T022314, start_date=20230923T022317, end_date=20230923T022340
[2023-09-23T02:23:56.187+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task get_jobs_from_api ('data'; 270)
[2023-09-23T02:23:56.241+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-09-23T02:23:56.296+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
