[2023-09-22T21:42:32.907+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: job_extraction_with_task_flow.create_cassandra_session manual__2023-09-22T21:42:30.678295+00:00 [queued]>
[2023-09-22T21:42:32.914+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: job_extraction_with_task_flow.create_cassandra_session manual__2023-09-22T21:42:30.678295+00:00 [queued]>
[2023-09-22T21:42:32.915+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-09-22T21:42:32.926+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): create_cassandra_session> on 2023-09-22 21:42:30.678295+00:00
[2023-09-22T21:42:32.930+0000] {standard_task_runner.py:57} INFO - Started process 352 to run task
[2023-09-22T21:42:32.934+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'job_extraction_with_task_flow', 'create_cassandra_session', 'manual__2023-09-22T21:42:30.678295+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/test3.py', '--cfg-path', '/tmp/tmpaq5i8g6s']
[2023-09-22T21:42:32.936+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask create_cassandra_session
[2023-09-22T21:42:32.949+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:188 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-09-22T21:42:32.979+0000] {task_command.py:410} INFO - Running <TaskInstance: job_extraction_with_task_flow.create_cassandra_session manual__2023-09-22T21:42:30.678295+00:00 [running]> on host 6d8bf768d09b
[2023-09-22T21:42:33.033+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='job_extraction_with_task_flow' AIRFLOW_CTX_TASK_ID='create_cassandra_session' AIRFLOW_CTX_EXECUTION_DATE='2023-09-22T21:42:30.678295+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-22T21:42:30.678295+00:00'
[2023-09-22T21:42:33.224+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test3.py", line 93, in create_cassandra_session
    return CassandraSessions(keyspace='job_data')
  File "/opt/airflow/dags/database.py", line 12, in __init__
    self.cluster = Cluster(nodes)
  File "cassandra/cluster.py", line 1191, in cassandra.cluster.Cluster.__init__
cassandra.UnresolvableContactPoints: {}
[2023-09-22T21:42:33.237+0000] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=job_extraction_with_task_flow, task_id=create_cassandra_session, execution_date=20230922T214230, start_date=20230922T214232, end_date=20230922T214233
[2023-09-22T21:42:33.243+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task create_cassandra_session ({}; 352)
[2023-09-22T21:42:33.267+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-09-22T21:42:33.282+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
