[2023-09-23T00:36:45.360+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: resume_generation_dag.generate_resume manual__2023-09-23T00:36:41.260604+00:00 [queued]>
[2023-09-23T00:36:45.367+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: resume_generation_dag.generate_resume manual__2023-09-23T00:36:41.260604+00:00 [queued]>
[2023-09-23T00:36:45.368+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-09-23T00:36:45.376+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): generate_resume> on 2023-09-23 00:36:41.260604+00:00
[2023-09-23T00:36:45.380+0000] {standard_task_runner.py:57} INFO - Started process 569 to run task
[2023-09-23T00:36:45.383+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'resume_generation_dag', 'generate_resume', 'manual__2023-09-23T00:36:41.260604+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/resume_generation.py', '--cfg-path', '/tmp/tmp4jk4mc2e']
[2023-09-23T00:36:45.386+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask generate_resume
[2023-09-23T00:36:45.397+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:188 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-09-23T00:36:45.424+0000] {task_command.py:410} INFO - Running <TaskInstance: resume_generation_dag.generate_resume manual__2023-09-23T00:36:41.260604+00:00 [running]> on host 43640a09cada
[2023-09-23T00:36:45.479+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='resume_generation_dag' AIRFLOW_CTX_TASK_ID='generate_resume' AIRFLOW_CTX_EXECUTION_DATE='2023-09-23T00:36:41.260604+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-23T00:36:41.260604+00:00'
[2023-09-23T00:37:02.518+0000] {logging_mixin.py:149} INFO - FULL_PATH
[2023-09-23T00:37:02.520+0000] {logging_mixin.py:149} INFO - /opt/***/dags/resumes/Resume_Software Engineer, Android | Ingenieur.e logiciel - Android_Meta.txt
[2023-09-23T00:37:12.172+0000] {logging_mixin.py:149} INFO - FULL_PATH
[2023-09-23T00:37:12.183+0000] {logging_mixin.py:149} INFO - /opt/***/dags/resumes/Resume_Software Engineer II - Machine Learning_Staples.txt
[2023-09-23T00:37:24.433+0000] {logging_mixin.py:149} INFO - FULL_PATH
[2023-09-23T00:37:24.446+0000] {logging_mixin.py:149} INFO - /opt/***/dags/resumes/Resume_Data Analyst/ Process Data Engineer/ Datawarehouse Analyst_Shorewise Consulting.txt
[2023-09-23T00:37:24.451+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/resume_generation.py", line 94, in generate_resume
    resume_gen(v['job_title'],",".join(v["skills"]),v['employer_name'],v['job_apply_link'])
  File "/opt/airflow/dags/resume_generation.py", line 55, in resume_gen
    with open(full_path, 'w') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/resumes/Resume_Data Analyst/ Process Data Engineer/ Datawarehouse Analyst_Shorewise Consulting.txt'
[2023-09-23T00:37:24.479+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=resume_generation_dag, task_id=generate_resume, execution_date=20230923T003641, start_date=20230923T003645, end_date=20230923T003724
[2023-09-23T00:37:24.492+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task generate_resume ([Errno 2] No such file or directory: '/opt/airflow/dags/resumes/Resume_Data Analyst/ Process Data Engineer/ Datawarehouse Analyst_Shorewise Consulting.txt'; 569)
[2023-09-23T00:37:24.515+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-09-23T00:37:24.527+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
